version: 1.0.{build}
image: Visual Studio 2017
install:
  - ps: Install-Product node 6
  - node --version
  - npm --version
  - npm install
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1
test: off
