//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Downloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Downloader.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string DefaultOutput {
            get {
                return ResourceManager.GetString("DefaultOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Async Completed.
        /// </summary>
        public static string Download_Async_Completed {
            get {
                return ResourceManager.GetString("Download_Async_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Async Started.
        /// </summary>
        public static string Download_Async_Started {
            get {
                return ResourceManager.GetString("Download_Async_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded to tmp: {0}.
        /// </summary>
        public static string Downloaded_to_tmp {
            get {
                return ResourceManager.GetString("Downloaded_to_tmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no handler for protocol {0}.
        /// </summary>
        public static string EWI001 {
            get {
                return ResourceManager.GetString("EWI001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to to process uri attemp {0} of {1} : {2}.
        /// </summary>
        public static string EWI002 {
            get {
                return ResourceManager.GetString("EWI002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri: {0}.
        /// </summary>
        public static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Any Key to Exit.
        /// </summary>
        public static string Press_Any_Key_to_Exit {
            get {
                return ResourceManager.GetString("Press_Any_Key_to_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered on DB: {0}{1}.
        /// </summary>
        public static string Registered_on_DB {
            get {
                return ResourceManager.GetString("Registered_on_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Downloading: {0}.
        /// </summary>
        public static string Start_Downloading {
            get {
                return ResourceManager.GetString("Start_Downloading", resourceCulture);
            }
        }
    }
}
